print('#'*60)
print("")
print('Olá,Mundo!'  )
print('')
print('Versão 1.0.2 aula 0002 29/05/2021')
variavel01 = "Professor josé Alberto Rodrigues"
print("")
print("Eu sou o...: %s\n \nObrigado por aprender Python!" %variavel01)
print("")
print("Eu vou mostrar como formatar a função print\n\nMeu nome é...: {} ".format(variavel01))
print('')
seunome = input(str("Qual seu nome....: "))
print("")
print('Estou aprendendo python!. Com o Professor {0}\n\nEu sou o aluno...: {1}'.format(variavel01,seunome))
print("")
fazerconta = input(str("Vamos fazer uma conta?...: "))
print('')
print("Quanto é 5/3?")
print('')
print(5/3)
print('')
print('Veja que o resultado está sem formatação!')
print('')
conta = 5/3
print("Agora vamos usar o format para colocar só duas casas depois da vírgula!")
print('')
print("O resultados é....: {:.2f}".format(conta))
print('')
print('#'*60)
